### ISSUE TITLE
Invalid 

### ISSUE THREAD

**Issue by Eydaxor** [Azuxul/UHCPluginBugTracker#1]
COUCOU TEAM BUGER MDRRRRRRRRRRR
[url=http://www.noelshack.com/2015-32-1438715054-2015-08-04-21-03-02.png][img]http://image.noelshack.com/minis/2015/32/1438715054-2015-08-04-21-03-02.png[/img][/url]

**Comment by Azuxul** [comment]
Les bugs report ne sont pas la pour s'amuser !
